import type { Metadata } from "next";
import type { ReactNode } from "react";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({ children }: { children: ReactNode }) {
    return (
        <div>
            <main>
                {children}
            </main>
        </div>
    );
}
